#!/bin/sh /etc/rc.common

START=91

USE_PROCD=1

boot() {
    FLAG_FILE="/etc/network_setup_done"

    if [ -f "$FLAG_FILE" ]; then
        echo "Network setup already applied."
        return 0
    fi

    uci set network.@globals[0].packet_steering='0'
    uci set network.@device[0].ports='eth1 eth2 eth3 eth4 eth5 eth6 eth7 eth8'
    uci set network.lan.ipaddr='192.168.10.1'
    uci set network.wan=interface
    uci set network.wan.proto='static'
    uci set network.wan.device='eth0'
    uci set network.wan.ipaddr='172.100.1.2'
    uci set network.wan.gateway='172.100.1.1'
    uci set network.wan.netmask='255.255.255.0'
    uci delete network.wan6
    uci commit
    reload_config

    # Create the flag file to indicate the script has run
    touch "$FLAG_FILE"
}
