#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1

boot() {
	uci set network.@device[0].ports='eth1 eth2 eth3 eth4 eth5 eth6'
	uci set network.lan.ipaddr='192.168.10.1'
	uci set network.wan=interface
	uci set network.wan.proto='dhcp'
	uci set network.wan.device='eth0'
	uci set network.wan6=interface
	uci set network.wan6.proto='dhcp6'
	uci set network.wan6.device='eth0'
	uci commit
	reload_config
	ls-addni dpmac.2
	ls-addni dpmac.3
	ls-addni dpmac.4
	ls-addni dpmac.5
	ls-addni dpmac.6
	ls-addni dpmac.7
	ls-addni dpmac.8
}

