#!/bin/sh /etc/rc.common

START=16

USE_PROCD=1

boot() {
    if ! uci show fstab | grep -q "target='/mnt/monitor'"; then
        uci add fstab mount
        uci set fstab.@mount[4].enabled='1'
        uci set fstab.@mount[4].device='/dev/mtdblock7'
        uci set fstab.@mount[4].target='/mnt/monitor'
        uci set fstab.@mount[4].fstype='jffs2'
        uci commit fstab
        reload_config
    fi
}